### ISSUE TITLE
Fix the bot periodically stops playing audio 

### ISSUE THREAD

**Issue by Fridenity** [Fridenity/Lyra#59]

**Comment by devbazregari** [comment]
hi, I'm hoping you're doing great. I haven't any experience with bots, but I know python and if you allow me I want to try to solve this issue.
can you tell me where are the files that relate to playing music?

**Comment by algonotion** [comment]
I think this is the file related to playing and pausing music.
https://github.com/Fridenity/Lyra/blob/main/lyra/src/modules/playback.py
